BEGIN;
DROP TABLE `album_document`;
DROP TABLE `album_album`;
DROP TABLE `album_taobaoitem`;
DROP TABLE `base_userprofile`;
DROP TABLE `base_userprofilemanager`;
DROP TABLE `django_session`;
ALTER TABLE `auth_user_groups` DROP FOREIGN KEY `user_id_refs_id_831107f1`;
ALTER TABLE `auth_user_user_permissions` DROP FOREIGN KEY `user_id_refs_id_f2045483`;
DROP TABLE `auth_user`;
DROP TABLE `auth_user_groups`;
DROP TABLE `auth_user_user_permissions`;
ALTER TABLE `auth_group_permissions` DROP FOREIGN KEY `group_id_refs_id_3cea63fe`;
DROP TABLE `auth_group`;
DROP TABLE `auth_group_permissions`;
DROP TABLE `auth_permission`;
DROP TABLE `django_content_type`;
DROP TABLE `django_site`;
COMMIT;
